const maindata = [
    {
        id: 1,
        title: "All",
        title2: "Recent",
        title3: "Music",
        title4: "Trending",
        title5: "Motivation",
        title6: "All",
        title7: "Recent",
        title8: "Music",
        title9: "Trending",
        title10: "Motivation",
        title11: "Music",
        title12: "Trending",
        title13: "Motive",
    },
    {
        id: 2,
        title: "Watched",
        title2: "Food",
        title3: "Live",
        title4: "Gaming",
        title5: "Thoughts",
        title6: "Watched",
        title7: "Food",
        title8: "Live",
        title9: "Gaming",
        title10: "Thoughts",
        title11: "Live",
        title12: "Gaming",
        title13: "Thoughts",
    },
    {
        id: 3,
        title: "Watched",
        title2: "News",
        title3: "Cricket",
        title4: "Trailer",
        title5: "Science",
        title6: "Watched",
        title7: "News",
        title8: "Cricket",
        title9: "Trailer",
        title10: "Science",
        title11: "Cricket",
        title12: "Trailer",
        title13: "Science",
    }
];
export default maindata